type Step {
    poisition: Int
    directions: String
}

input StepInput {
    poisition: Int
    directions: String
}

type Section {
    poisition: Int
    title: String
    steps: [Step]
}

input SectionInput {
    poisition: Int
    title: String
    steps: [StepInput]
}

type Activity {
    _id: ID
    title: String
    description: String
    sections: [Section]
    postscript: String
}

input ActivityInput {
    title: String
    description: String
    sections: [SectionInput]
    postscript: String
}
