type Step {
    directions: String
}

input StepInput {
    directions: String
}

type Section {
    title: String,
    steps: [Step]
}

input SectionInput {
    title: String,
    steps: [StepInput]
}

type Activity {
    _id: ID,
    title: String,
    description: String,
    sections: [Section],
    postscript: String
}

input ActivityInput {
    title: String,
    description: String,
    sections: [SectionInput],
    postscript: String
}
